import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from 'constants/navigation.constant'

const navigationConfig = [
    {
        key: 'overview',
        path: '/overview',
        title: 'Overview',
        translateKey: 'nav.overview',
        icon: 'overview',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'projectdashboard',
        path: '/projectdashboard',
        title: 'Project Dashboard',
        translateKey: 'nav.projectdashboard',
        icon: 'projectdashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'hired',
        path: '/hired',
        title: 'Hired',
        translateKey: 'nav.hired',
        icon: 'hired',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'tasks',
        path: '',
        title: 'Tasks',
        translateKey: 'nav.tasks',
        icon: 'tasks',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'tasks.tasks',
                path: '/tasks',
                title: 'Task',
                translateKey: 'nav.tasks.task',
                icon: 'task',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'tasks.scrumboard',
                path: '/scrumboard',
                title: 'Scrumboard',
                translateKey: 'nav.tasks.Scrumboard',
                icon: 'scrumboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'standups',
        path: '/standups',
        title: 'Standups',
        translateKey: 'nav.standups',
        icon: 'standups',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: '1on1',
        path: '/1on1',
        title: '1 on 1s',
        translateKey: 'nav.1on1',
        icon: 'oneon1',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'performance',
        path: '/performance',
        title: 'Performance',
        translateKey: 'nav.performance',
        icon: 'performance',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'timesheets',
        path: '/timesheets',
        title: 'Timesheets',
        translateKey: 'nav.timesheets',
        icon: 'timesheets',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'headquarters',
        path: '/headquarters',
        title: 'Headquarters',
        translateKey: 'nav.headquarters',
        icon: 'headquarters',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'manageteams',
        path: '/manage-teams',
        title: 'Manage Teams',
        translateKey: 'nav.manageteams',
        icon: 'teams',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'settings',
        path: `/settings/profile`,
        title: 'Settings',
        translateKey: 'settings',
        icon: 'settings',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
]

export default navigationConfig
